//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RESX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RESX() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API.Shared.Resources.RESX", typeof(RESX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار CName صحیح نمیباشد.
        /// </summary>
        public static string CNameIsNotValid {
            get {
                return ResourceManager.GetString("CNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دامنه وارد شده صحیح نیست.
        /// </summary>
        public static string DomainIsInvalid {
            get {
                return ResourceManager.GetString("DomainIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل تکراری است.
        /// </summary>
        public static string EmailIsDuplicate {
            get {
                return ResourceManager.GetString("EmailIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل درست نیست.
        /// </summary>
        public static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس IP درست نیست.
        /// </summary>
        public static string IPv4AddressIsNotValid {
            get {
                return ResourceManager.GetString("IPv4AddressIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس آی پی اشتباه است.
        /// </summary>
        public static string IPv6AddressIsNotValid {
            get {
                return ResourceManager.GetString("IPv6AddressIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای دامنه های عمومی حداقل طول نام باید چهار کاراکتر باشد.
        /// </summary>
        public static string MinimumNameLengthForPublicDomainIsFour {
            get {
                return ResourceManager.GetString("MinimumNameLengthForPublicDomainIsFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل تکراری است.
        /// </summary>
        public static string MobileIsDuplicate {
            get {
                return ResourceManager.GetString("MobileIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل درست نیست.
        /// </summary>
        public static string MobileIsNotValid {
            get {
                return ResourceManager.GetString("MobileIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این قابلیت پشتیبانی نمیشود.
        /// </summary>
        public static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور قبلی درست نیست.
        /// </summary>
        public static string OldPasswordIsWrong {
            get {
                return ResourceManager.GetString("OldPasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور باید بیشتر از 8 کاراکتر باشد.
        /// </summary>
        public static string PasswordMustBeMoreThan8Character {
            get {
                return ResourceManager.GetString("PasswordMustBeMoreThan8Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت یافت نشد.
        /// </summary>
        public static string PaymentNotFound {
            get {
                return ResourceManager.GetString("PaymentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات رکورد یافت نشد.
        /// </summary>
        public static string RecordDataNotFound {
            get {
                return ResourceManager.GetString("RecordDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد تکراری است.
        /// </summary>
        public static string RecordIsDuplicate {
            get {
                return ResourceManager.GetString("RecordIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام رکورد ضروری است.
        /// </summary>
        public static string RecordNameIsRequired {
            get {
                return ResourceManager.GetString("RecordNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد یافت نشد.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع رکورد یافت نشد.
        /// </summary>
        public static string RecordTypeNotFound {
            get {
                return ResourceManager.GetString("RecordTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید منقضی شده است.
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام توکن یافت نشد.
        /// </summary>
        public static string TokenNameIsRequired {
            get {
                return ResourceManager.GetString("TokenNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید یافت نشد.
        /// </summary>
        public static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای هر توکن حداقل یک رکورد باید انتخاب شود.
        /// </summary>
        public static string TokenRecordsCannotBeEmpty {
            get {
                return ResourceManager.GetString("TokenRecordsCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید قبلا استفاده شده است.
        /// </summary>
        public static string TokenUsedBefore {
            get {
                return ResourceManager.GetString("TokenUsedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیتای رکود TXT اشتباه است.
        /// </summary>
        public static string TxtRecordDataCannotBeEmpty {
            get {
                return ResourceManager.GetString("TxtRecordDataCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر امکان اضافه کمردن رکورد جدید وجود ندارد.
        /// </summary>
        public static string UnableToAddRecordAtThisTime {
            get {
                return ResourceManager.GetString("UnableToAddRecordAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر امکان ایجاد Zone وچود ندارد.
        /// </summary>
        public static string UnableToCreateZoneAtThisTime {
            get {
                return ResourceManager.GetString("UnableToCreateZoneAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر امکان حذف رکورد وجود ندارد.
        /// </summary>
        public static string UnableToDeleteRecordAtThisTime {
            get {
                return ResourceManager.GetString("UnableToDeleteRecordAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر امکان حذفZone وچود ندارد.
        /// </summary>
        public static string UnableToDeleteZoneAtThisTime {
            get {
                return ResourceManager.GetString("UnableToDeleteZoneAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر امکان غیر فعال یا فعالسازی رکورد وجود ندارد.
        /// </summary>
        public static string UnableToDisableRecordAtThisTime {
            get {
                return ResourceManager.GetString("UnableToDisableRecordAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر امکان غیر فعالسازی Zone وچود ندارد.
        /// </summary>
        public static string UnableToDisableZoneAtThisTime {
            get {
                return ResourceManager.GetString("UnableToDisableZoneAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر امکان فعالسازی Zone وچود ندارد.
        /// </summary>
        public static string UnableToEnableZoneAtThisTime {
            get {
                return ResourceManager.GetString("UnableToEnableZoneAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر امکان ویرایش کمردن رکورد وجود ندارد.
        /// </summary>
        public static string UnableToUpdateRecordAtThisTime {
            get {
                return ResourceManager.GetString("UnableToUpdateRecordAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری تکراری است.
        /// </summary>
        public static string UsernameIsDuplicate {
            get {
                return ResourceManager.GetString("UsernameIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری درست نیست.
        /// </summary>
        public static string UsernameIsNotValid {
            get {
                return ResourceManager.GetString("UsernameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        public static string UsernameOrPasswordIsWrong {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone تکراری است.
        /// </summary>
        public static string ZoneIsDuplicate {
            get {
                return ResourceManager.GetString("ZoneIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone یافت نشد.
        /// </summary>
        public static string ZoneNotFound {
            get {
                return ResourceManager.GetString("ZoneNotFound", resourceCulture);
            }
        }
    }
}
